server:
 port: 8083

# Configuración de SQL (comentada correctamente)
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/powerup
#     username: root
#     password: 1234
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/trazabilidad

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
